version: "3.8"
services:
  app:
    build: .
    image: example/order-service:0.0.1
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      # reduce JVM memory for dev if desired:
      - JAVA_TOOL_OPTIONS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=60.0
